Repository USB-CI3715/nodebb-usb-24-dummy, pull requests merged in 2024-10, with the labels that each got.

#33 Inclusión de archivo "src/messaging/edit.js" generado por la traducción del Proyecto 1
  src/dummy.js
  src/messaging/edit.js
Labels: enhancement

#35 Eliminación de comentarios "eslint-disable" para los archivos del proyecto 1. Solución a lentitud de "./nodebb setup".
  src/messaging/edit.js
  src/posts/data.js
Labels: File Change

#37 Inclusión de archivo "src/messaging/unread.js" generado por la traducción del Proyecto 1
  src/messaging/unread.js
Labels: File Change

#36 HU1 y HU2 (Back-End) - Inclusión y modificación de Rol para profesores/teacher, validación de creación de materias.
  src/cli/user.js
  src/groups/create.js
  src/groups/index.js
  src/privileges/global.js
  src/privileges/helpers.js
  src/privileges/teacher.js
  src/privileges/users.js
  src/upgrades/1.0.0/teachers.js
  src/user/create.js
  src/user/index.js
Labels: Enhancement

#39 Modificación de la vista de registro.tpl para tomar en cuental el rol del usuario
  nodebb-plugin-theme-harmony/templates/register.tpl
  public/language/en-GB/register.json
  public/language/en-US/register.json
  public/language/es/register.json
Labels: Enhancement
