Repository USB-CI3715/nodebb-usb-24-dummy, pull requests merged in 2024-11, with the labels that each got.

#41 Inclusión de campos en la vista modal mostrada al crear una materia
  public/language/en-GB/groups.json
  public/language/en-US/groups.json
  public/language/es/groups.json
  public/src/client/groups/list.js
Labels: Enhancement, File Change

#46 Actualización de Traducciones en groups.json
  public/language/en-GB/groups.json
  public/language/en-US/groups.json
  public/language/es/groups.json
Labels: Enhancement, File Change

#61 Inclusión de funcionalidad de creación de categoría cuando se crea una matería
  src/api/categories.js
  src/api/groups.js
Labels: File Change, New Feature

#43 Soluciones y Pruebas realizadas al problema de lentitud de Setup en NodeBB
  doc_solutions_setup.txt
  install/package.json
Labels: Bug, Documentation, File Change

#62 Inclusión de funcionalidad que elimina la categoría asociada al curso
  src/api/groups.js
Labels: File Change, New Feature

#63 Cambia el nombre y la descripción de las categorías predeterminadas
  install/data/categories.json
Labels: Enhancement, File Change, Change Feature

#64 Modifies title of website in nodebb-plugin-theme-harmony/templates/partials/header/brand.tpl
  install/data/categories.json
  nodebb-plugin-theme-harmony/templates/partials/header/brand.tpl
Labels: File Change, Change Feature

#69 Personalización de la descripción de la categoría generada al momento de crear un curso
  src/api/groups.js
Labels: File Change, Change Feature

#70 Manejo de errores de los campos Código y Nombre en la ventana modal de creación de Materias
  public/language/en-GB/error.json
  public/language/en-US/error.json
  public/language/es/error.json
  public/src/client/groups/list.js
Labels: File Change, New Feature

#71 Eliminación automática de cursos y categorías en caso de quedar sin propietarios en el grupo
  src/api/groups.js
Labels: File Change, Change Feature

#72 Eliminación automática de cursos si un Administrador elimina una categoría
  src/api/categories.js
Labels: File Change, Change Feature

#77 Inclusión de nuevo campo en el formulario de registro para solicitar el nombre completo.
  nodebb-plugin-theme-harmony/templates/register.tpl
  public/language/en-GB/error.json
  public/language/en-GB/register.json
  public/language/en-US/error.json
  public/language/en-US/register.json
  public/language/es/error.json
  public/language/es/register.json
  public/openapi/read/topic/topic_id.yaml
  public/src/client/register.js
  public/src/modules/helpers.common.js
  src/api/groups.js
  src/groups/membership.js
  src/user/create.js
  src/user/settings.js
  test/user.js
Labels: File Change, New Feature, Change Feature

#78 Se añaden tests para probar la creación de un usuario con rol de profesor en test_dummy/rol-teacher.js y archivos necesarios para el funcionamiento de los tests
  test/user.js
  test_dummy/.eslintrc
  test_dummy/mocks/databasemock.js
  test_dummy/mocks/plugin_modules/@nodebb/another-thing/package.json
  test_dummy/mocks/plugin_modules/@nodebb/another-thing/plugin.json
  test_dummy/mocks/plugin_modules/@nodebb/nodebb-plugin-abc/package.json
  test_dummy/mocks/plugin_modules/@nodebb/nodebb-plugin-abc/plugin.json
  test_dummy/mocks/plugin_modules/nodebb-plugin-xyz/package.json
  test_dummy/mocks/plugin_modules/nodebb-plugin-xyz/plugin.json
  test_dummy/mocks/plugin_modules/something-else/package.json
  test_dummy/mocks/plugin_modules/something-else/plugin.json
  test_dummy/rol-Teacher-FrontEnd-ByAndreaDiaz.js
  test_dummy/rol-teacher.js
Labels: File Change, Change Feature

#82 Inclusión de casos de prueba Rol-Teacher-VersiónBackEnd a la nueva Suit de pruebas
  src/api/groups.js
  test_dummy/rol-Teacher-BackEnd-ByJuniorLara.js
  test_dummy/rol-Teacher-FrontEnd-ByAndreaDiaz.js
Labels: File Change, File Create, New Tests

#81 Removes group title truncate in user badge
  nodebb-plugin-theme-harmony/templates/partials/groups/badge.tpl
  test_dummy/rol-teacher.js
Labels: 2-3 Hours, File Change

#83 Inclusión de pruebas para ventana modal de creación de materias, registro de usuario con nuevo campo `fullname` y nombre de materias desplegado
  test_dummy/course-creation-modal-ByAstridAlvarado.js
  test_dummy/display-group-name-ByAstridAlvarado.js
  test_dummy/registration-user-ByAstridAlvarado.js
Labels: File Create, New Tests

#84 Modificacion de configuracion de pruebas ESlint para los casos de prueba en la carpeta `test_dummy/`
  test_dummy/.eslintrc
  test_dummy/course-creation-modal-ByAstridAlvarado.js
  test_dummy/registration-user-ByAstridAlvarado.js
Labels: File Change, Change Feature

#85 Se mueven los tests de rol-teacher.js a rol-Teacher-FrontEnd-ByAndreaDiaz.js
  test_dummy/rol-Teacher-FrontEnd-ByAndreaDiaz.js
  test_dummy/rol-teacher.js
Labels: File Change, New Tests

#87 agregar pruebas para permisos de acceso a grupos globales
  test_dummy/group-permissions-byLuisGarcia.js.js
Labels: 2-3 Hours

#89 Arreglo de filtrado de posts de un curso
  src/api/groups.js
Labels: File Change, New Feature

#86 Documentación de UserGuide.md con todas las especificaciones necesarias
  UserGuide.md
Labels: Documentation, File Change
